<?php
/**
 * Created by PhpStorm.
 * User: Matthew
 * Date: 2019/2/14
 * Time: 20:25
 */

namespace app\index\controller\common;

use think\Controller;
use think\session;

/**
 * 用于书写一些通用的方法
 * Class Base
 * @package app\index\controller
 */
class Base extends Controller
{
    /**
     * 可以定义控制器初始化方法_initialize，在该控制器的方法调用之前首先执行
     * 这样就不需要在其他controller在书写执行代码了
     */
    public function _initialize()
    {
        $nowTime = time();
        $s_time = session('loginTime');
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('nickName')) {
            return $this->error('您没有登陆', url('index/index'));
        }

        /**
         * 判断登录时间
         */
        if (($nowTime - $s_time) > 36000) {
            session('loginTime', null);
            $this->error('当前用户未登录或登录超时，请重新登录', U('/index/index'));
        } else {
            /**
             * 更新检测时间
             * 这样可以避免对应的数据进行
             */
            session('loginTime', $nowTime);
        }
    }
}