<?php
/**
 * Created by PhpStorm.
 * User: Matthew
 * Date: 2019/2/14
 * Time: 20:25
 */

namespace app\index\controller\common;

use think\Controller;
use think\session;

/**
 * 用于书写一些通用的方法
 * Class Base
 * @package app\index\controller
 */
class Base extends Controller
{
    /**
     * 可以定义控制器初始化方法_initialize，在该控制器的方法调用之前首先执行
     * 这样就不需要在其他controller在书写执行代码了
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('nickName')) {
            return $this->error('您没有登陆', url('index/index'));
        }
    }
}